<div class="wrap">
<h2>Raygun4WP Configuration</h2>
<p>This plugin is the official provider for the Raygun.io error reporting service. It allows you to easily send and track errors that are generated by your Wordpress site.</p>
<p>You need to have a raygun.io account created to use this service - if you do not have one, visit <a href="http://raygun.io">http://raygun.io</a> for more information and to create an account. A 60-day free trial is available.</p>
<p>To get started, visit <a href="https://app.raygun.io">app.raygun.io</a> and copy your application's API key from its Settings page. Then, enter it below and turn error reporting on.</p>

<form method="post" action="options.php">
<?php wp_nonce_field( 'update-options' ); ?>

    <table class="form-table">
        <tr valign="top">
        <th scope="row">Error Reporting Status</th>
        <td>
		<select name="rg4wp_status">
		  <option value="0"<?php echo ! get_option( 'rg4wp_status' ) ? ' selected="selected"': '';?>>Disabled</option>
		  <option value="1"<?php echo get_option( 'rg4wp_status' ) ? ' selected="selected"': '';?>>Enabled</option>
		</select>

<tr valign="top">
        <th scope="row">API Key</th>
        <td><input type="text" size="60" name="rg4wp_apikey" value="<?php echo get_option( 'rg4wp_apikey' ); ?>" /></td>
        </tr>
	</td>
</tr>
</table>
<input type="hidden" name="action" value="update" />
<input type="hidden" name="page_options" value="rg4wp_status,rg4wp_apikey" />
    
<?php submit_button(); ?>
</form>
<a href='rghomepage.php'>Find out more about Raygun and sign up here</a>
</div>